spring:
  application:
    name: teacher-service
  datasource:
    url: jdbc:mysql://192.168.0.103:3306/huifan?&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#    url: jdbc:mysql://139.9.246.95:3306/huifan?&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
#    password: hfed1302
    password: Huifan@2019
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-connect-error-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
        session-stat-enable: true
        session-stat-max-count: 1000
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
  redis:
    host: 192.168.0.100
    port: 6379
    timeout: 10000
    database: 0
    lettuce:
      pool:
        max-wait: 1
        max-idle: 8
        max-active: 8
        min-idle: 0
    password: huiFan@2019
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath*:/mybatis/mappers/*.xml
  type-aliases-package: com.zjhz.parentsservice.domain
  config-location: classpath:mybatis/mybatis-config.xml

server:
  port: 8083

logging:
  config: classpath:log4j2.xml
  level:
    root: info

hbase:
  zookeeper:
   quorum: huifan-cloudtable-zk1-3m0YZaag.cloudtable.com:2181,huifan-cloudtable-zk3-gIjBNpzw.cloudtable.com:2181,huifan-cloudtable-zk2-ayoZdwMS.cloudtable.com:2181
   port: 2181