spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:mysql://localhost:3306/zjhz_cs_platform?&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-connect-error-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
        session-stat-enable: true
        session-stat-max-count: 1000
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    database: 0
    lettuce:
      pool:
        max-wait: 1
        max-idle: 8
        max-active: 8
        min-idle: 0
    password: 123456
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath*:/mybatis/mappers/*.xml
  type-aliases-package: com.zjhz.authentication.domain
  config-location: classpath:mybatis/mybatis-config.xml

server:
  port: 8082

logging:
  config: classpath:log4j2.xml
  level:
    root: info

redisTime: 12